<a href="https://colab.research.google.com/github/19PA1A0269/AI-lab/blob/master/Experment_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# experiment-1 numpy

In [ ]:
import numpy as mp

## Different ways to create numpy

###   Creating numpy by using list

In [ ]:
a=mp.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b=mp.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


##  Add remove modify elements in an array

 ### Adding elements in an arrays

In [ ]:
p=mp.append([1,2,3,4],a)
print(p)

[1 2 3 4 1 2 3]


### Remove elements in an array

In [ ]:
p=mp.array([[1,2,3,5],[6,7,8]])
print(p)

[list([1, 2, 3, 5]) list([6, 7, 8])]


In [30]:
mp.delete(p,1,0)

array([list([1, 2, 3, 5])], dtype=object)

### Modify elements in array

In [ ]:
q=mp.array([[0.567,0.678,0.243],[0.975,0.912,0.134],[0.589,0.147,0.129]])
q[q>0.5]=0.1
print(q)

[[0.1   0.1   0.243]
 [0.1   0.1   0.134]
 [0.1   0.147 0.129]]


### Arithmetic operations on numpy arrays

In [ ]:
f=mp.random.randint(50,size=3)
g=mp.random.randint(50,size=3)
print(f)
print(g)

[38 40 11]
[10 25 24]


In [ ]:
sum=mp.add(f,g)
row=mp.multiply(f,g)
sub=mp.subtract(f,g)
div=mp.divide(f,g)
mod=mp.mod(f,g)
print(sum)
print(row)
print(sub)
print(div)
print(mod)

[48 65 35]
[ 380 1000  264]
[ 28  15 -13]
[3.8        1.6        0.45833333]
[ 8 15 11]


 ## slicing and iterating of numpy array

### slicing the numpy arrays

In [31]:
a=mp.array([1,2,3,4,5,6,7,8,9])
print(a[0:5])

[1 2 3 4 5]


In [33]:
b=mp.array([1,2,3,4,5,6,7,8,9,0])
print(b[0:5:2])

[1 3 5]


### Iterating the numpy array

In [35]:
b=mp.array([[1,2,3],[4,5,6]])
for n in b:
 print(n)

[1 2 3]
[4 5 6]


In [37]:
d=([1,2,3,4,5,6,7,8,9])
for q in d:
 print(q)

1
2
3
4
5
6
7
8
9


## Matrix Operaters in numpy

In [39]:
a=mp.array([1,2,3,4])
b=mp.array([5,6,7,8])
sum=mp.add(a,b)
sub=mp.subtract(a,b)
pro=mp.multiply(a,b)
div=mp.divide(a,b)
print(a)
print(b)
print(sum)
print(sub)
print(pro)
print(div)

[1 2 3 4]
[5 6 7 8]
[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
